[font]
size = 13.5

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
dynamic_title = true

[window.padding]
x = 15
y = 15

[env]
TERM = "xterm-256color"
