general {
    col.active_border = rgba(B746B3ff) rgba(03020Eff) 45deg
    col.inactive_border = rgba(322931ff) rgba(682255ff) 45deg
}

group {
    col.border_active = rgba(322931ff) rgba(682255ff) 45deg
    col.border_inactive = rgba(05050Acc) rgba(000317cc) 45deg
    col.border_locked_active = rgba(42293Eff) rgba(54264Aff) 45deg
    col.border_locked_inactive = rgba(04040Ecc) rgba(020313cc) 45deg
}
